### ISSUE TITLE
Improve the content and flow of the backend readme 

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool#1022]
### Problem

As I went to follow the the readme to set up the backend for the second time for local dev. I ran into issues again which I had to take @jbair06 precious time to help get it going. I took lots of notes and used it to rebuild the readme for the backend thinking from the perspective of how does a developer complete this in tasks and make it really easy as well as comprehensive like including screenshots where we can so its easy to reference what it being said in text. 

### Solution

Improve the readme such that a new developer can get going without getting stuck or the need to communicate with someone.

**Comment by SvetBorislavov** [comment]
I agree that the example.env should be prefilled with the default values, but we should not have a "default" .env files.
We should leave the users to create them

**Comment by SvetBorislavov** [comment]
Fixed in #1351
