### ISSUE TITLE
Test Node transactions with solo after custom public networks are available

### ISSUE THREAD

**Issue by Sheng-Long** [hashgraph/hedera-transaction-tool#1064]
### Problem

Node Create, Update, and Delete transactions are not currently fully testable without using custom public networks and solo.

### Solution

Once the custom public networks is complete, the Node transactions should be tested with solo.

**Comment by SimiHunjan** [comment]
The node create, update and delete transactions were tested to return successful. Was not tested end to end in Solo with the additional steps like the freeze transactions etc.
