### ISSUE TITLE
Validate user flows

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool#1069]
### Problem

- Update file 101, 102, 121 ,111, 123 in the local node
- Add a custom Solo network
- Verify the DAB transactions in pre production network

### Solution

Verify the above flows

**Comment by SvetBorislavov** [comment]
- System files TESTED
- Solo network is supported with the 'Local Node' button in the network settings

**Comment by SvetBorislavov** [comment]
Is the third one testing on the staging custom networks?

**Comment by jbair06** [comment]
This issue was resolved in https://github.com/hashgraph/hedera-transaction-tool/pull/1086 and https://github.com/hashgraph/hedera-transaction-tool/pull/1382. 

Solo works if you select 'local node'. #1399 and #1400 have been created in order to better track the requirements.
