### ISSUE TITLE
Empty or Missing Catch Statements

### ISSUE THREAD

**Issue by jbair06** [hashgraph/hedera-transaction-tool#1136]
### Problem

Some instances of a try block were found where no catch exists. This is likely not an issue, but should be reviewed. An example can be found in front-end/src/renderer/pages/UserLogin/UserLogin.vue#127 (the line may vary). 

### Solution

Review usage of try block. Add catch if potential error can be consumed by the try block.

**Comment by SvetBorislavov** [comment]
Fixed in #1361
