### ISSUE TITLE
Add feature to resend new user emails

### ISSUE THREAD

**Issue by jbair06** [hashgraph/hedera-transaction-tool#1147]
### Problem

If the new user email is lost, or never sent, there is no current way to resend that email. An admin should be able to resend the email.

### Solution

- add a button in the frontend to allow admins to resend the new user email
- add an admin guarded route in the backend to enable the resending of the email. This route will need the email of the new user.

**Comment by SimiHunjan** [comment]
made a dupe here #1290 . Will close it in favor of this one.

**Comment by SimiHunjan** [comment]
Recreate the password when the new email is sent.
