### ISSUE TITLE
Improve clarity for users during recovery phrase verification process

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-transaction-tool#1192]
### Problem

While generating a new key and verifying that I had recorded the recovery phrase, I was confused because I did not know what I was supposed to do next. Once I verified that I had recorded the recovery phrase and clicked "Next", the "Next" button disappeared, I did not see that some recovery words had been cleared, and I did not know that I was supposed to fill in the ones there were cleared.

### Solution

1. Add text on the screen explaining that the user must fill in the empty boxes with the correct recovery phrases
2. Do not remove the "Next" button. It should always be visible but disabled. This is an indication to the user that action is required before the button can be pushed.
3. Highlight or otherwise visually distinguish the boxes that need to be filled in.

**Comment by SimiHunjan** [comment]
Thanks for the issue @poulok ! Great suggestions!

**Comment by SimiHunjan** [comment]
Review other ecosystem wallets to get some inspiration
