### ISSUE TITLE
Update the Transaction Tool deployments to not use managed services

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool#1209]
### Problem

Today, the Transaction Tool deployments use managed services. 

### Solution

Update to not use the managed services.

**Comment by RAMTO** [comment]
@SimiHunjan Please provide more details regarding this issue.

**Comment by jbair06** [comment]
Our devops team setup some of the services to be hosted by GCP. We've been asked to move the Postgres service back into the kluster, along with any other host service that we can. This issue was created for the the Devops team.

**Comment by SimiHunjan** [comment]
The outcome of this issue is that managed services will continue to be used when we are not at scale with deploying this service. When at scale we will consider moving away from managed services.
