### ISSUE TITLE
Screen size issues especially with smaller screens

### ISSUE THREAD

**Issue by jbair06** [hashgraph/hedera-transaction-tool#1240]
It has been observed that a number of windows, pages, or popups exist that have a minimum size smaller than the actual space required and are not scrollable. Need some examples of this issue.

**Comment by SimiHunjan** [comment]
We should test the app and all screens on a mac book air or consider reducing an available whitespace

**Comment by SimiHunjan** [comment]
Test the registration flow and make the application window really small. Minimum screen size has also been changed to help improve this. May not see the issue anymore because of the change.

**Comment by SimiHunjan** [comment]
Believe this issue should be resolved now. We will reopen if users mention the same issue in the future.
