### ISSUE TITLE
Add mnemonic nickname mapping

### ISSUE THREAD

**Issue by jbair06** [hashgraph/hedera-transaction-tool#1246]
When a mnemonic is inputed, a nickname should be requested from the user. This would allow a user to quickly and easily see which keys belong to which mnemonic. If mnemonic hashes are salted, this because a bit more difficult. This needs concept needs to be thought through.

**Comment by SvetBorislavov** [comment]
We can still use nicknames even with salted mnemonics.
When you go to key generation and enter a mnemonic, it can be compared to the already added mnemonic hashes and if there is a match, it will take its nickname, if there isn't a match a prompt for the nickname can be requested
