### ISSUE TITLE
Improve keychain explanation

### ISSUE THREAD

**Issue by jbair06** [hashgraph/hedera-transaction-tool#1251]
Users are confused by the keychain usage and what it covers. The keychain modal should include more information as to what it is for.

**Comment by SimiHunjan** [comment]
Combine the email and password option to login to the application with the key chain option visible in the same window.

**Comment by jbair06** [comment]
Also, 'sign in' is not what we're wanting, unless the user is actually signing in because they chose the username/password option during initial setup.

**Comment by SimiHunjan** [comment]
Thanks for posting the examples @jbair06 !
