### ISSUE TITLE
DAB transaction updates

### ISSUE THREAD

**Issue by jbair06** [hashgraph/hedera-transaction-tool#1268]
The DAB transaction flows need to be updated with the changes discovered in the Transaction Tool v1 implementation.

- Both Gossip and GRPC certificates should allow both a copy/paste input or browse to the file location.
  - Certificates need to have a newline at the end. Validation needs to be added to ensure that the newline exists, or add it if it does not.
- Both Gossip and GRPC certificates should show a hash in hex below the input
  - Gossip cert should show the hash of the public key of the cert
  - GRPC cert should show the hash of the cert itself 

Need to make sure that the proper info is being hashed. For Gossip, this is the actual cert object, not the string content nor the file itself. For GRPC, this is the actual string content of the certificate.

**Comment by jbair06** [comment]
In java, the Gossip certificate is converted from text input to the bytes:
`try (var parser = new PEMParser(new StringReader(certificate))) {
			var parserObject = parser.readObject();
			if (parserObject instanceof X509CertificateHolder) {
				var certificateHolder = (X509CertificateHolder) parserObject;
				return new JcaX509CertificateConverter().getCertificate(certificateHolder).getEncoded();
			}
			throw new CertificateException(
					"Not X509 Certificate, it is " + parserObject.getClass().getSimpleName());
		} catch (IOException | CertificateException e) {
			throw new HederaClientRuntimeException(e);
		}`

**Comment by jbair06** [comment]
To convert the Gossip Cert string input to bytes in Java is done like this:
```
try (var parser = new PEMParser(new StringReader(certificate))) {
	var parserObject = parser.readObject();
	if (parserObject instanceof X509CertificateHolder) {
		var certificateHolder = (X509CertificateHolder) parserObject;
		return new JcaX509CertificateConverter().getCertificate(certificateHolder).getEncoded();
	}
	throw new CertificateException(
			"Not X509 Certificate, it is " + parserObject.getClass().getSimpleName());
} catch (IOException | CertificateException e) {
	throw new HederaClientRuntimeException(e);
}
```

**Comment by jbair06** [comment]
To convert the GRPC Cert string input to hash in Java is done like this:
```
public static byte[] hashCertificate(String certificate) {
	var certificateBytes = certificate.getBytes(StandardCharsets.UTF_8);
	return hashBytes(certificateBytes);
}
```

**Comment by SimiHunjan** [comment]
https://github.com/hashgraph/hedera-sdk-js/blob/main/src/NodeCerts.js
