### ISSUE TITLE
Node certificate is not saved in drafts

### ISSUE THREAD

**Issue by yiliev0** [hashgraph/hedera-transaction-tool#1301]
### Description

After filling in details for node transaction, saving it as draft and navigating back to the draft transaction -> node certificate is not saved

### Steps to reproduce

1. Navigate to node create transaction
2. Fill in node account id, gossip domain and port, certificate and admin key
3. Save it as draft
4. Navigate to transaction -> drafts
5. Open the last saved draft 

Expected result: All saved inputs are present after opening the draft 
Actual result: Gossip certificate is not saved

### Version

0.5

### Operating system

macOS

**Comment by jbair06** [comment]
This is related to #1286. Looks like both @SvetBorislavov and @Sheng-Long are working this separately.
