### ISSUE TITLE
Update Personal Information screen

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool#1311]
### Problem

![IMG_4338](https://github.com/user-attachments/assets/6f3f3551-f2e4-4dd4-bcfb-c215c0a05f0a)

### Solution

Title: Authentication
Description: Login with an email and password or select the keychain option

Remove encryption mode and the credentials and keychain options.

Leave email and password fields. Underneath these fields add the Keychain option. The button selection can be "Use Keychain". The user can select "Use Keychain" or enter an email and password.

**Comment by SvetBorislavov** [comment]
Fixed in #1380
