### ISSUE TITLE
Style improvements in Accounts/Files & Key Migration

### ISSUE THREAD

**Issue by icoxxx** [hashgraph/hedera-transaction-tool#1379]
### Problem

This issue addresses the need for consistent button placement, style adjustments, and heading size corrections across the Accounts, Files, and Key Key Selection step during migration.

### Solution

-Accounts Page

Remove Button Visibility:
The "Remove" button should only be visible when the "Select" button is not active.
If the "Select" button is active, the "Remove" button should be relocated underneath the "Select" button for better alignment and clarity (with smaller width/height).

- Files Page

Select Button Consistency:
Update the "Select" button style to match the design and behavior of the "Select" button on the Accounts Page for a consistent user experience + the same logic for the 'Remove' button.

- Key Selection step during migration

Heading Size Adjustment:
The second heading during the key selection step is currently larger than intended.
Reduce the size of this heading to align with the correct heading hierarchy and style guidelines.

**Comment by SvetBorislavov** [comment]
Additionally make the "Select all" text next to the checkbox clickable
