### ISSUE TITLE
Possible Resource Exhaustion via Upload Key feature

### ISSUE THREAD

**Issue by jbair06** [hashgraph/hedera-transaction-tool#720]
We found that the product does not properly control the allocation and maintenance of a limited resource, thereby enabling an actor to influence the amount of resources consumed, eventually leading to the exhaustion of available resources via the upload key feature. The upload key REST api does not enforce any rate limit and an attacker who has admin level permission, can abuse the API to upload many keys. Also, there is no key size or length restriction where an attacker can upload any length or size key via API.

**Comment by SvetBorislavov** [comment]
Fixed with #1315
