### ISSUE TITLE
investigate multi-node signing solution

### ISSUE THREAD

**Issue by jbair06** [hashgraph/hedera-transaction-tool#759]
The SDK function for addSignature doesn't work in a multi-node situation. But adding the same signature to each sub transaction (where a sub transaction is the same as the main transaction but has the node ID specified by the sdk) shouldn't work either as the node ID is part of the transaction that is signed. 

Some more research needs to be done to properly handle the adding, and possible removing, of signatures from a transaction that has multiple nodes.

**Comment by SvetBorislavov** [comment]
Fixed with #1023
