### ISSUE TITLE
investigate proper signing method in a multi signature flow

### ISSUE THREAD

**Issue by jbair06** [hashgraph/hedera-transaction-tool#760]
If a signature is added to a transaction, any other signers that sign that transaction will then have a signature that is only valid with the transaction that has the previously created signatures. This means that all signers should sign the base transaction.

If the above is true, then further investigation is required to ensure that the signatures that are created will pass verification when submitted.

**Comment by SvetBorislavov** [comment]
@jbair06 We believe this is done
